# Generated by Django 3.0.4 on 2020-03-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='naverData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=200)),
                ('buy_num', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogData',
        ),
    ]
